env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules:
  no-param-reassign: 0
  react/prop-types: 0
  import/extensions: 0
  jsx-a11y/label-has-associated-control: 0
